import "@/styles/globals.css";
import { StoreProvider } from "@/utils/Store";
import { ThemeProvider } from "next-themes";
import { SessionProvider, useSession } from "next-auth/react";
import { Raleway } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});
export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <>
      <Head>
        <title>Next Takealot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${raleway.variable} font-raleway`}>
        <ThemeProvider enableSystem={true} attribute="class">
          <SessionProvider session={session}>
            <StoreProvider>
              {Component.auth ? (
                <Auth>
                  <Component {...pageProps} />
                </Auth>
              ) : (
                <Component {...pageProps} />
              )}
            </StoreProvider>
          </SessionProvider>
        </ThemeProvider>
      </main>
    </>
  );
}
// protected route
function Auth({ children }) {
  const router = useRouter();
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      router.push("/unauthorized?message=login required");
    },
  });

  if (status === "loading") {
    return <div>Loading...</div>;
  }
  return children;
}